### ISSUE TITLE
Make a master branch to deploy to Pages

### ISSUE THREAD

**Issue by andrewlitfin** [IGME-RIT/igme-rit.github.io#2]
The [documentation for GitHub Pages](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages) states that for an Organization Pages site, 

> You must use the `username.github.io` naming scheme.
> Content from the `master` branch will be used to build and publish your GitHub Pages site.

Currently, we do not have a `master` branch, only a `dev` branch.  When the site is ready to go live, we should make a `master` branch, and probably tag it as `v1` or something like that.

**Comment by Erbelding** [comment]
There is now a master branch.

Master will only contain the "build" of the site, not the actual project.
